#! /usr/local/bin/python3.9
# main.py
import sys

print("\nRXA609: recognize Acurite 609 pulse patterns from an .ook file\n")

if len(sys.argv)>=2:
    fn = sys.argv[1]
else:
    fn = input("Path/Name to file to be processed: ")

if not(fn.endswith(".ook") or fn.endswith(".OOK")):
    fn = fn + ".ook"
print("Processing file ", fn)

f = open(fn, "rt")

while (line := f.readline() ):
    if not line.startswith(";"):
        values = line.split()
        e0 = int(values[0])
        e1 = int(values[1])
        print("{:>5d},{:>5d}".format(e0,e1))
    
"""        if line.endswith("\n"):
           print(line, end="")
        else:
           print(line)
"""
    
